{% set name = "FRETBursts" %}
{% set version = "0.5.7" %}
{% set sha256 = "5ee6a90e3e99b76709c1f2e3f8137c7ac96faaebe8a593b64ac2599f3884292e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/tritemio/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [win32 and py35]
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - future
    - cython
    - numpy x.x
    - matplotlib
    - seaborn
    - lmfit
    - phconvert

  run:
    - python
    - future
    - numpy x.x
    - scipy
    - pyqt 4*
    - matplotlib
    - seaborn
    - pandas
    - numba
    - lmfit
    - phconvert

test:
  imports:
    - fretbursts
    - fretbursts.phtools.phrates

about:
  home: http://tritemio.github.io/FRETBursts/
  license: GPLv2
  license_file: LICENSE.txt
  summary: 'Burst analysis software for single-molecule FRET experiments.'
  description: |
    FRETBursts is a open source software for burst analysis of freely-diffusing
    single-molecule FRET (smFRET) experiments.
  doc_url: http://fretbursts.readthedocs.io/
  dev_url: https://github.com/tritemio/FRETBursts

extra:
  recipe-maintainers:
    - tritemio
