travis:
  secure:
    BINSTAR_TOKEN: b5rND7qFqRW3wjZd04Xh5kTGBOs2+2a77xcS5oZ5TcNLQ7RSKeIUk7OkQa+DZCgD9Mn0aD+ayEGptB4YjWRTm+ilcS+FCfsorfb5wJ6sYDVJ9S1a651D0fTnN6MmaQ6FClkaAYBjfWZ+7Yq/MBTljIb+kJdn6pkiRla0LjPXhP1+RNAXtXKD2pfEW62gXW8WaWUQX5r5AswYpoIZ8271kq7yGNUtVE+6Ysi+S24rOjoIOuAT0vuI+SAK3iPP7YHs88juAeRtshTxgkxdK4E6JgAyxeUrry1p9ZqMYCzkPvmAOucnrLdJ3kfTIX5DN5r7t3OEm6P4DwmHLwbeoOGMoqa+OrzYYcNM4Hq2+En051LmTmRXzI/YrWnUiRSb61a0ZprgjYbMX/TIOJTO6WR3Ji2BzKIizcbfSFvOg+1IUnvbWy3/pzyENU1+qCxv8NDKPlsGz/9t9bPhendpjcB2FxVZoi9Nxyd3QFsF3Rb5EcRahYgq0tKQlrds1eFf/2f6oSLZhkC2fGvypmWMcaGP4nyZP1OvCyuLoBVAvy19VHd0IlPObzAYWs4NEqg1rOAJ0FtbjXEmHr6y4goH6TgfPEAeVdZ9K8TQfE1FB7hyw2/kGnOwhVM28NC/DEkiRXyX5/mT7TMbAf1d8tlmYNrOC8qAlWrrn0l6aZRh0K5hsOE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
