travis:
  secure:
    BINSTAR_TOKEN: tIj8d87Os2FtLqOTwYdD0nGn07Ojw2YLyj06y0yY+ii4nai+BVIY+0M/HhcPyHcVvXsQMhe5DMAXFOAcA4k5+HeSuffTvPE8TNpJPh3y3lOLErkAJEsEuuiBR9+CTtJdw2XaAn/zEy09ZjK7V6nqQVYHqD1LcADxBMOifLQXkTQFI4rvX7tIOHnB1ISBYExizQ0S763MmRuGN/ARIlTgpFsVCud3V+OlxWqc3UYHZsrgmUjdzAAYJJ97ZRh4F3LqvP7WjiiKrFJQm50I+VJHOE2PiHH+Lh0B/919fAytODO6DqqHLuj1dBsZvx0x8SBAw5I2D7Bo4PYWQkJHE04E1y4MRUyqqJjgCEOQDtFHVgDg/JHagOoFdb/dP0zev21Fn8la8o1+jsUo+MGzBYriMDf4Ck4c4n380IR7JPH4g6ZrPkmvl10YOCv6GuBIZnJuxleSiK1Mbs22ZO9p7LW6PWP+AuX6kYLHM+1hPzWUtjX6ZyGpN03Q+SR/nzORox9EW1rVfOFiUiZRbq+frrIq6UPbWLVxvYXOxh1XiK8tjkr7e+kQDo6VgO8Fa4dbdq75412mO6kIHDI75fmqLwqDb2NFA7Wp8a1gTQJAIhAv2TfqrHuAiyVkrfgSdA/Z647qnAv9dkIpyIwIYrxJLJMvLSw5RvX9K2LO1T7iyt4wZL0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
