travis:
  secure:
    BINSTAR_TOKEN: QzdW6gE5gGSRJVRxRt5bPxZp5+8xSPYkF6PDRs8TMRYgT0v5t3Vm6fPjv7qOGr0Bpu+3c65xorIN0le0tGgHjoanEIHGLTrI3d8iUtJ2DKyDP1WrlcE7k7PyeUdg7K4RA0jjv0izI4mPL/RX8Jr3hgnuUdYOxNtuiTFyYISD+K3XwhXkscEy6Bln9IGesytih8D+knlDGPg9UxkvLUj5dTozRkouJuEV3GeiH+HkAmTx2beNbuJbz7u6pwDGg5ODHokJQ6DUGenzsceqrl7oqRu+Zf20rqKUhQfNn63u1edaffTZidLxYcmrlmPEmEi+s9btMcSbckkhiUu2uUYxucBVzUuCqi7uwAsF2N4Ffm9VwemlWNo1cuMHH1qLw28yvCgRp4XNrekYSRTisPPOdxuF0V8d3EQFuQ5O58BpOkj4AjDozThFSR+VmlegcfaqyO/HpqMFpRPkPaSeBup3mC5QQovq8MNJQeQ1SEgH/pyTBOYpEOaTnLQvTNWr7NPy6gPH/BjXz0MXmmP/MZrC8Jiq5G8PAJjFcerO+fAdYg28D95zy6R0ENd+G13iG1PjBh/oRVlJxuAKckwM/1Kh7iIRQEymlx9Xz69sspgpuMmKDoBUKjt84K7lCH2i/5zkD7bvEaxFIoppSZbejbN2UKlxj4FbIZ18//q0yehrJY0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
